

# druid连接池
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/day01
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis -彻底抛弃mybatis-config.xml
# mapperxml文件的位置  settings的配置  别名的配置...
mybatis:
  mapper-locations: classpath:/mappers/*.xml  #指定xml文件的位置
  type-aliases-package: com.atguigu.pojo
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
